import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const clientSource = await readFile(new URL('../tavern-plugin/lib/client.js', import.meta.url), 'utf8')
const serverSource = await readFile(new URL('../tavern-plugin/lib/index.js', import.meta.url), 'utf8')
const presetConversionSource = await readFile(new URL('../tavern-plugin/lib/domain/preset-conversion-preview.js', import.meta.url), 'utf8')

function between(source, start, end) {
  const from = source.indexOf(start)
  const to = source.indexOf(end, from)
  assert.notEqual(from, -1, `missing start marker: ${start}`)
  assert.notEqual(to, -1, `missing end marker: ${end}`)
  return source.slice(from, to)
}

test('卡片模式从空白工作台直接进入 Agent 对话', () => {
	const flow = between(clientSource, 'async function newCardConversation', 'function formatTime')
	const lifecycle = between(clientSource, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const recovery = between(clientSource, 'async function finishPendingOpen', 'async function retryPendingOpen')

	assert.doesNotMatch(flow, /window\.prompt/)
	assert.match(lifecycle, /call\("getResourceWorkspace"\)/)
	assert.match(serverSource, /case 'getResourceWorkspace': return \{ path: dataRoot \+ '\/resources' \}/)
	assert.match(lifecycle, /props\.workspaces\.create\(\{ path: resourceRoot\.path \}\)/)
	assert.match(lifecycle, /connectWorkspace: function/)
	assert.match(lifecycle, /call\("startChat"/)
	assert.match(lifecycle, /rememberPending: setPendingOpen/)
	assert.match(lifecycle, /finishOpen: finishPendingOpen/)
	assert.match(flow, /conversationLifecycle\.start/)
	assert.match(flow, /kind: "card", targetMode: "card"/)
	assert.match(recovery, /publishSessionMode\(pending\.sessionId, pending\.targetMode\)/)
  assert.match(recovery, /props\.openCardLibraryTab\(pending\.sessionId\)/)
  assert.match(recovery, /props\.openResourcesTab\(pending\.sessionId\)/)
  assert.ok(recovery.indexOf('props.openCardLibraryTab(pending.sessionId)') < recovery.indexOf('props.openResourcesTab(pending.sessionId)'))
})

test('游玩回复可只读交给同人物卡的卡片 Agent 调试', () => {
	const renderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')
	const status = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

	assert.doesNotMatch(renderer, /交给卡片 Agent 调试|dsh-tavern-assistant-debug/)
	assert.match(status, /感觉内容有问题？/)
	assert.match(status, /openPlayChatDebugWorkspace\(props\.sessionId, latestDebugTurn\)/)
	assert.match(status, /交给卡片 Agent 调试/)
	assert.doesNotMatch(status, /selectedDebugTurn|setDebugTurn|第 " \+ item\.turn \+ " 轮/)
	assert.match(clientSource, /dsh-tavern-debug-play-chat/)
	assert.match(sidebar, /getPlayChatDebugTarget/)
	assert.match(sidebar, /attachPlayChatDebug/)
	assert.match(sidebar, /"debug-play", "调试游玩对话"/)
	assert.match(serverSource, /name: 'tavern_read_play_chat'/)
	assert.match(serverSource, /case 'attachPlayChatDebug'/)
	assert.match(serverSource, /createPlayChatDebugReference/)
})

test('新建对话会确认 Tavern preset 以恢复被复用的冷 Session Agent', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const guard = between(sidebar, 'async function ensureTavernPreset', 'async function archiveCurrentBlankSession')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function importCard')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

  assert.match(guard, /agentPresets\.select/)
	assert.doesNotMatch(guard, /agentPreset === "tavern"\) return/)
	assert.match(lifecycle, /ensurePreset: ensureTavernPreset/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
  assert.doesNotMatch(playFlow, /agentPresets\.select/)
  assert.doesNotMatch(cardFlow, /agentPresets\.select/)
})

test('新建游玩和卡片对话等待前端 Session 列表就绪后再继续', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const waitFlow = between(sidebar, 'async function waitForSessionSummary', 'function isUnknownSessionSelectError')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function importCard')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

  assert.match(waitFlow, /props\.sessions\.list\.getSnapshot\(\)\.byId\[sessionId\]/)
  assert.match(waitFlow, /DSH Session 列表同步超时/)
	assert.match(lifecycle, /waitForSession: waitForSessionSummary/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
})

test('已创建 Session 在前端列表短暂不同步时刷新并重连同一个 Session', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const waitFlow = between(sidebar, 'async function waitForSessionSummary', 'function isUnknownSessionSelectError')
  const openFlow = between(sidebar, 'async function openSessionWhenReady', 'async function finishPendingOpen')

  assert.match(waitFlow, /props\.sessions\.binding\(sessionId\)/)
  assert.match(openFlow, /typeof props\.sessions\.refresh === "function"/)
  assert.match(openFlow, /isUnknownSessionSelectError\(error\)/)
  assert.match(openFlow, /await waitForSessionSummary\(sessionId\)/)
  assert.match(openFlow, /props\.sessions\.open\(sessionId\)/)
  const normalPath = openFlow.slice(0, openFlow.indexOf('catch (error)'))
  assert.doesNotMatch(normalPath, /sessions\.refresh|waitForSessionSummary/)
  assert.doesNotMatch(openFlow, /connectWorkspace|startChat/)
})

test('游玩中可修改玩家称呼，Tavern 不接管正文发送状态', () => {
  const player = between(clientSource, 'function TavernPlayerNameAction', 'function TavernStatusPanel')

  assert.match(serverSource, /async function setPlayerName\(sessionId, userName\)/)
  assert.match(serverSource, /playerName: str\(chat\.macroState && chat\.macroState\.userName\)\.trim\(\) \|\| '你'/)
  assert.match(serverSource, /case 'setPlayerName'/)
  assert.match(player, /rpc\("setPlayerName", \{ userName: next \}, props\.sessionId\)/)
  assert.match(player, /仅影响之后生成的内容/)
  assert.match(clientSource, /id: "dsh-tavern-player-name"/)
  assert.doesNotMatch(clientSource, /TavernSignalTimeoutNotice/)
  assert.doesNotMatch(clientSource, /dsh-tavern-signal-timeout/)
})

test('后台协调快照不参与 Session 恢复、页面重载或正文锁定', () => {
  assert.doesNotMatch(serverSource, /case 'getSessionConnection'/)
  assert.match(serverSource, /case 'syncSession'/)
  assert.match(serverSource, /runtimeGeneration/)
  assert.match(serverSource, /agentRegistry\.get\(str\(args && args\.sessionId\)\)/)
  assert.doesNotMatch(clientSource, /createComposerGate/)
  assert.doesNotMatch(clientSource, /createRuntimeVersionGuard/)
  assert.doesNotMatch(clientSource, /createRuntimeConnectionCoordinator/)
  assert.doesNotMatch(clientSource, /conversation\.blocks/)
  assert.doesNotMatch(clientSource, /dsh-tavern:runtime-generation:v1/)
  assert.doesNotMatch(clientSource, /dsh-tavern:reconnect-draft:v1/)
})

test('新开游玩在创建 Session 前完成游戏准备，创建后不提供开场白切换器', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const prepareFlow = between(sidebar, 'async function preparePlayConversation', 'async function importCard')

  assert.match(sidebar, /getCardOpenings/)
  assert.match(sidebar, /上一条开场白/)
  assert.match(sidebar, /下一条开场白/)
  assert.match(sidebar, /以此开场/)
  assert.match(sidebar, /游戏准备/)
	  assert.match(sidebar, /故事中的玩家称呼（可选）/)
	  assert.match(sidebar, /selectedOpening && selectedOpening\.usesUser/)
	  assert.match(sidebar, /不填则使用“你”/)
	  assert.match(serverSource, /usesUser: \/\\\{\\\{\\s\*user\\s\*\\\}\\\}\/i\.test\(opening\.text\)/)
  assert.match(sidebar, /dsh-tavern-player-name/)
  assert.match(sidebar, /preparePlayConversation\(card\)/)
  assert.doesNotMatch(prepareFlow, /connectWorkspace|startChat/)
  assert.match(sidebar, /newConversation\(openingPicker\.card, null, selectedOpening \? selectedOpening\.id : "", openingPicker\.userName \|\| "你"\)/)
  assert.match(sidebar, /openingId: openingId \|\| ""/)
  assert.match(sidebar, /userName: resolvedUserName/)
  assert.match(sidebar, /dsh-tavern-picker-overlay/)
  assert.match(sidebar, /role: "dialog"/)
	assert.match(sidebar, /h\("iframe"/)
	assert.match(sidebar, /selectedOpening && openingPicker\.openings\.length > 1 \? h\("iframe"/)
	assert.match(sidebar, /srcDoc: buildOpeningPreviewDocument/)
	assert.match(sidebar, /sandbox: "allow-scripts allow-forms allow-modals allow-downloads allow-popups allow-popups-to-escape-sandbox"/)
	assert.doesNotMatch(sidebar, /展示页不可作为开场/)
})

test('开场白创建失败时在选择弹窗内持续显示具体阶段和错误', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const refresh = between(sidebar, 'function refresh()', 'React.useEffect(function ()')
  const playFlow = between(sidebar, 'async function newConversation', 'async function preparePlayConversation')
  const lifecycle = between(clientSource, 'function createConversationLifecycleModule', 'function isIgnoredTavernError')

  assert.match(sidebar, /const pickerError = error \? h\("div", \{ className: "dsh-tavern-picker-error", role: "alert" \}/)
  assert.match(sidebar, /重新连接已创建的 Session/)
  assert.match(sidebar, /const playPicker = h\("div",[^\n]+pickerError/)
  assert.match(sidebar, /!picking && error \? h\("div", \{ className: "dsh-tavern-dock-error", role: "alert" \}/)
  assert.doesNotMatch(refresh, /setError\(""\)/)
  assert.match(lifecycle, /let phase = "清理当前空白对话"/)
  assert.match(lifecycle, /phase = "创建 DSH Session"/)
  assert.match(lifecycle, /phase = request\.kind === "card" \? "创建卡片工作台对话" : "写入人物卡开场白"/)
  assert.match(lifecycle, /failure\.phase = phase/)
  assert.match(playFlow, /err && err\.phase/)
})

test('Tavern 错误面板只保留最新错误，左侧栏连接恢复后撤销轮询错误', () => {
  const errorHub = between(clientSource, 'const tavernErrorHub', 'function usePersistentError')
  const errorCenter = between(clientSource, 'function TavernErrorCenter', 'const tavernSessionModes')
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(errorHub, /\.slice\(0, 1\)/)
  assert.match(errorHub, /const existing = items\[0\]/)
  assert.match(errorHub, /count: existing\.count \+ 1/)
  assert.doesNotMatch(errorHub, /slice\(0, 20\)/)
  assert.match(errorHub, /dismiss: function \(id\)/)
  assert.match(errorHub, /resolve: function \(source\)/)
  assert.match(errorHub, /clear: function \(\)/)
  assert.doesNotMatch(errorHub, /setTimeout|setInterval/)
  assert.match(errorHub, /window\.sessionStorage\.getItem\(storageKey\)/)
  assert.match(errorHub, /window\.sessionStorage\.setItem\(storageKey, JSON\.stringify\(items\)\)/)
  assert.match(errorCenter, /最新错误/)
  assert.doesNotMatch(errorCenter, /复制全部|全部清除/)
  assert.match(errorCenter, /"复制"/)
  assert.match(errorCenter, /"清除"/)
  assert.match(clientSource, /const lastReported = React\.useRef\(""\)/)
  assert.match(clientSource, /visible !== lastReported\.current/)
  assert.match(clientSource, /if \(!visible\) tavernErrorHub\.resolve\(source\)/)
  assert.match(sidebar, /if \(collapsed\) return h\(React\.Fragment, null,\s*h\(TavernErrorCenter\)/)
  assert.match(sidebar, /return h\(React\.Fragment, null, h\(TavernErrorCenter\)/)
  assert.match(clientSource, /usePersistentError\("左侧栏操作"\)/)
  assert.match(sidebar, /tavernErrorHub\.resolve\("左侧栏"\)/)
  assert.match(sidebar, /tavernErrorHub\.report\("左侧栏", err\)/)
  assert.match(clientSource, /usePersistentError\("剧本库"\)/)
  assert.match(clientSource, /usePersistentError\("预设库"\)/)
  assert.match(clientSource, /usePersistentError\("人物卡库"\)/)
  assert.match(clientSource, /usePersistentError\("人物卡详情"\)/)
  assert.match(clientSource, /usePersistentError\("剧本管理"\)/)
  assert.match(clientSource, /usePersistentError\("Guide"\)/)
  assert.match(clientSource, /usePersistentError\("酒馆状态"\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("候选项生成", err\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("正文重新生成", err\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("插件更新", err\)/)
  assert.match(clientSource, /function isIgnoredTavernError\(value\)/)
  assert.match(errorHub, /if \(isIgnoredTavernError\(error\)\) return/)
  assert.match(clientSource, /const visible = isIgnoredTavernError\(message\) \? "" : message/)
  assert.match(clientSource, /setLocalError\(visible\)/)
})

test('展示投影通过正式 assistant-step renderer 渲染，并在配置变化后重算历史', () => {
  const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
  const renderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')

  assert.match(serverSource, /function replyProjectionsOf\(chat\)/)
  assert.match(view, /projectRuntimeReplyHistory\(chat\.messages/)
  assert.match(view, /replyProjections: replyDisplay\.projections/)
  assert.match(renderer, /key: "assistant-step"/)
  assert.match(renderer, /priority: -1/)
  assert.match(renderer, /useLiveTavernView\(props\.sessionId/)
  assert.match(renderer, /tavernProjectionForTurn\(liveState\.view, turn\)/)
  assert.doesNotMatch(clientSource, /function applyReplyProjections|dsh-tavern-projected-reply/)
})

test('候选项列表限制高度并独立滚动，底部操作保持在滚动区外', () => {
  const question = between(clientSource, 'function CandidateQuestion', 'function CandidateGuidePanel')

  assert.match(clientSource, /\.dsh-tavern-question-body \{ max-height: min\(360px, 45vh\); overflow-y: auto;/)
  assert.match(question, /className: "dsh-tavern-question-body"/)
  assert.ok(question.indexOf('className: "dsh-tavern-question-body"') < question.indexOf('className: "dsh-tavern-question-foot"'))
})

test('后台结算期间禁用候选项按钮，完成后自动恢复', () => {
  const action = between(clientSource, 'function CandidateAction', 'function CandidateDockActions')
  const coordination = between(clientSource, 'const tavernCoordination', 'function describeTavernActivity')
  const submit = between(clientSource, 'async function submitCandidateTask', 'const regenPanel')
  const guide = between(clientSource, 'function CandidateGuidePanel', 'function RegenPanel')
  const activity = between(serverSource, 'async function sessionActivity', 'async function sessionView')

  assert.match(serverSource, /case 'syncSession'/)
  assert.match(serverSource, /case 'submitTask'/)
  assert.match(activity, /const activity = backgroundTasks\.activity\(chat\)/)
  assert.doesNotMatch(activity, /settleStatus/)
  assert.doesNotMatch(activity, /view\(|readChatCard|projectRuntimeReplyHistory/)
  assert.doesNotMatch(clientSource, /dsh-tavern-activity-gate/)
  assert.match(action, /useTavernCoordination\(props\.sessionId/)
  assert.match(action, /disabled:.*activity\.busy/s)
  assert.match(action, /disabled: false, title: "重新生成正文/)
  assert.match(action, /disabled: rolling, title: "删除最近一次用户输入/)
  assert.match(clientSource, /"后台结算中…"/)
  assert.match(action, /props\.refreshSessions\(\)/)
  assert.match(action, /submitCandidateTask\(props\.sessionId, props\.messageId, guidance\)/)
  assert.match(guide, /submitCandidateTask\(props\.sessionId, messageId, guide\)/)
  assert.doesNotMatch(clientSource, /rpc\("generateChoices"/)
  assert.match(submit, /rpc\("submitTask"/)
  assert.match(submit, /tavernCoordination\.setView\(sessionId/)
  assert.match(coordination, /new window\.EventSource/)
  assert.doesNotMatch(coordination, /rpc\("syncSession"|setTimeout|setInterval/)
  assert.doesNotMatch(serverSource, /case 'generateChoices'/)
  assert.doesNotMatch(action, /rpc\("getSession"/)
})

test('人物卡详情支持查看、绑定和解绑唯一世界书', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')
  const dispatch = between(serverSource, 'async function dispatch', 'const webServer')

  assert.match(dispatch, /case 'getWorldBookBinding'/)
  assert.match(dispatch, /case 'bindWorldBook'/)
  assert.match(dispatch, /case 'unbindWorldBook'/)
  assert.match(panel, /call\("getWorldBookBinding", \{ cardPath: cardPath \}\)/)
  assert.match(panel, /call\("listWorldBooks"\)/)
  assert.match(panel, /"人物卡自带世界书"/)
  assert.match(panel, /call\("bindWorldBook", \{ cardPath: cardPath, source: source \}\)/)
  assert.match(panel, /call\("unbindWorldBook", \{ cardPath: cardPath \}\)/)
  assert.match(panel, /const hasWorldBookBinding = Boolean/)
  assert.match(panel, /hasWorldBookBinding \? null : h\("select"/)
  assert.match(panel, /hasWorldBookBinding \? null : h\("button", \{ className: "dsh-tavern-script-primary"/)
  assert.match(panel, /props\.onOpenWorldBook\(worldBookBinding\.source\)/)
  assert.match(panel, /"打开世界书"/)
})

test('新建对话把缺失的当前空 Session 视为已归档', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const archiveBlank = between(sidebar, 'async function archiveCurrentBlankSession', 'async function waitForSessionSummary')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function preparePlayConversation')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

  assert.match(archiveBlank, /props\.workspaces\.archiveSession\(current\)/)
  assert.match(archiveBlank, /if \(!isMissingSessionArchiveError\(archiveError\)\) throw archiveError/)
	assert.match(lifecycle, /archiveCurrent: archiveCurrentBlankSession/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
})

test('创建对话失败时服务端记录请求边界但不记录开场白正文', () => {
  const dispatch = between(serverSource, 'async function dispatch', 'const webServer')

  assert.match(dispatch, /console\.error\('dsh-tavern: 创建对话失败'/)
  assert.match(dispatch, /cardPath: str\(args && args\.path\)/)
  assert.match(dispatch, /openingId: str\(args && args\.openingId\)/)
  assert.doesNotMatch(dispatch, /greeting|openingText/)
})

test('卡片模式通过人物卡、剧本、世界书、预设和空白入口进入同一个 Agent', () => {
  const flow = between(clientSource, 'async function newCardConversation', 'function formatTime')
  const recovery = between(clientSource, 'async function finishPendingOpen', 'async function retryPendingOpen')

  assert.match(clientSource, /"修改人物卡"/)
  assert.match(clientSource, /"从剧本新建人物卡"/)
  assert.match(clientSource, /"修改剧本"/)
  assert.match(clientSource, /"修改世界书"/)
  assert.match(clientSource, /"修改预设"/)
  assert.match(clientSource, /仅编辑，无法使用/)
  assert.match(clientSource, /"空白开始"/)
	assert.doesNotMatch(clientSource, /请先从右侧侧边栏的对应资源库导入人物卡、剧本、世界书或预设文件。/)
	assert.match(clientSource, /initialImportLabel = cardEntry === "worldbook" \? "导入世界书"/)
	assert.match(clientSource, /cardEntry === "extract" \|\| cardEntry === "script" \? "导入剧本"/)
	assert.match(clientSource, /importInitialResource\(f, cardEntry\)/)
	assert.match(clientSource, /暂无可选.*可点击右上角导入/)
	assert.match(flow, /kind: "card", targetMode: "card"/)
  assert.match(flow, /task: task, label: label, card: card, selectedResources: selectedResources \|\| \[\]/)
  assert.match(recovery, /if \(pending\.task\) await props\.injectTaskPrompt\(pending\.sessionId, pending\.task, pending\.label, pending\.card, \(pending\.selectedResources \|\| \[\]\)\.length > 0\)/)
  assert.doesNotMatch(clientSource, /startExtract|newExtractSession|"revision"|mode: "extract"/)
  assert.doesNotMatch(clientSource, /attachSourcesToCurrent|attachCardToCurrent/)
  assert.match(clientSource, /return values\[sessionId\] \|\| "";/)
})

test('世界书与预设起始任务先选择一个目标并自动追加类型引用', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /call\("listWorldBooks"\)/)
  assert.match(sidebar, /call\("listPresets"\)/)
  assert.match(sidebar, /newCardConversation\(null, "worldbook", "修改世界书"/)
  assert.match(sidebar, /newCardConversation\(null, "preset", "修改预设"/)
  assert.match(sidebar, /kind: "worldbook"/)
  assert.match(sidebar, /kind: "preset"/)
})

test('世界书库在卡片对话中可引用独立或内置世界书', () => {
  const panel = between(clientSource, 'function createWorldBookLibraryFeatureModule', 'const worldBookLibraryFeature')

  assert.match(panel, /props\.appendMention\("worldbook"/)
  assert.match(panel, /在对话中引用/)
  assert.match(panel, /sessionMode === "card"/)
  assert.match(clientSource, /tavern-worldbook:/)
})

test('人物卡抽取与剧本修改都使用剧本库，并自动追加引用', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const recovery = between(sidebar, 'async function finishPendingOpen', 'async function retryPendingOpen')

  assert.match(sidebar, /async function openResourcePicker\(task\)/)
  assert.match(sidebar, /const response = await call\("listResources"\)/)
  assert.match(sidebar, /kind: "source"/)
  assert.match(sidebar, /initialResourceGroup\(initialResourceTitle, initialResources\)/)
  assert.doesNotMatch(sidebar, /initialResourceGroup\("素材"/)
  assert.doesNotMatch(sidebar, /initialResourceGroup\("已绑定剧本"/)
  assert.match(sidebar, /disabled: busy \|\| !chosenInitialResources\.length/)
  assert.match(sidebar, /newCardConversation\(null, "extract", "从剧本新建人物卡", chosenInitialResources\)/)
  assert.match(sidebar, /newCardConversation\(null, "script", "修改剧本", chosenInitialResources\)/)
  assert.match(recovery, /\(pending\.selectedResources \|\| \[\]\)\.forEach/)
  assert.match(recovery, /props\.appendMention\(pending\.sessionId, resource\.kind, resource\.path, resource\.title\)/)
  assert.doesNotMatch(recovery, /pending\.task === "boundary"/)
  assert.match(sidebar, /先选择一份剧本，再进入工作台修改工作版/)
  assert.doesNotMatch(sidebar, /newCardConversation\(null, "extract", "从素材新建人物卡"\);/)
})

test('卡片任务只在创建对话时追加提示词，不占用输入框上方区域', () => {
  assert.match(clientSource, /rpc\("getCardTaskPrompt", \{ task: task \}, sessionId\)/)
  assert.match(clientSource, /【目标人物卡】/)
  assert.match(clientSource, /card && card\.path/)
  assert.match(clientSource, /@\\"/)
  assert.match(clientSource, /input\.setDraft\(taskText \+ supplement\)/)
  assert.match(clientSource, /task === "worldbook" \|\| task === "preset"/)
  assert.match(clientSource, /【初始剧本】/)
  assert.match(clientSource, /【编辑目标】/)
  assert.doesNotMatch(clientSource, /【补充要求】/)
  assert.doesNotMatch(clientSource, /function CardTaskDockActions/)
  assert.doesNotMatch(clientSource, /id: "dsh-tavern-card-tasks"/)
  assert.doesNotMatch(clientSource, /choose\("bindScript"/)
})

test('空白工作台确认后自动创建人物卡，不再提供二次保存按钮', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.doesNotMatch(clientSource, /CardDraftPanel|finalizeCard|保存为新人物卡|写入草稿/)
  assert.doesNotMatch(serverSource, /case 'finalizeCard'/)
  assert.match(sidebar, /const currentSummary = current \? summaries\[current\] : null;/)
  assert.match(sidebar, /if \(!currentSummary \|\| currentSummary\.blank\) return;\s*notifyDataChanged\(\);/)
})

test('Tavern 只接管会话区域，保留 DSH 原生设置与模型配置入口', () => {
  assert.match(clientSource, /slots\.inject\("sidebar\.workspaces"/)
  assert.doesNotMatch(clientSource, /slots\.inject\("sidebar",/)
})

test('游玩不提供多开场白切换器', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  assert.doesNotMatch(sidebar, /switchOpening\(|call\("switchOpening"/)
})

test('酒馆状态页注册到 Better Sidebar，不再接管 DSH details', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function CardFieldsPanel')

  assert.match(sidebar, /readyTavernSession/)
  assert.match(sidebar, /summaries\[current\]\.blank === false/)
  assert.match(sidebar, /history\.some\(function \(entry\) \{ return entry\.sessionId === current && isPlayMode\(entry\.mode\); \}\)/)
  assert.match(sidebar, /props\.openStatusTab\(readyTavernSession\)/)
  assert.match(sidebar, /props\.openStatusTab\(pending\.sessionId\)/)
  assert.match(clientSource, /ctx\.betterSidebar\.registerTab\(\{/)
  assert.match(clientSource, /id: "dsh-tavern:status"/)
  assert.match(clientSource, /patch: \{ panelOpen: true \}/)
  assert.doesNotMatch(clientSource, /className: "dsh-tavern-status-presentation"/)
  assert.doesNotMatch(clientSource, /buildOpeningPreviewDocument\(view\.presentation\.html\)/)
  assert.match(clientSource, /ctx\.betterSidebar\.openTab\(\{ type: "dsh-tavern:status" \}/)
  assert.doesNotMatch(clientSource, /slots\.inject\("details"|openDetails|ensureDetailsOpen/)
})

test('左侧栏提供一键更新并展示 CLI、Desktop 与 Android 的不同提示', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /call\("getUpdateStatus"/)
  assert.match(sidebar, /call\("startUpdate"/)
  assert.match(sidebar, /更新到最新版/)
  assert.match(sidebar, /正在比较本地版本与 GitHub 最新版本/)
  assert.match(sidebar, /已是最新提交/)
  assert.match(sidebar, /tavern-update-probe/)
  assert.match(sidebar, /recovery\.sawOffline/)
  assert.match(sidebar, /window\.location\.reload\(\)/)
  assert.match(sidebar, /程序文件已更新，但自动重启失败/)
  assert.match(sidebar, /请手动重启/)
  assert.match(sidebar, /更新期间会短暂断开/)
  assert.match(sidebar, /如果较长时间仍未更新完成，建议重新安装一次/)
  assert.match(sidebar, /检测到 Git 时只会下载运行所需代码/)
  assert.match(sidebar, /请重启 DSH Desktop/)
  assert.match(sidebar, /更新完成，请刷新页面/)
  assert.match(sidebar, /Android 版/)
  assert.match(sidebar, /3088/)
  assert.match(sidebar, /未知方法:\s*getUpdateStatus/)
  assert.match(sidebar, /请重启 DSH Desktop 以加载新版插件/)
  assert.match(sidebar, /重启 Desktop 后可用/)
  assert.match(serverSource, /case 'getUpdateStatus'/)
  assert.match(serverSource, /case 'startUpdate'/)
})

test('持久化的更新完成状态不是刷新命令，页面只在服务实际离线恢复后刷新一次', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /recovery\.sawOffline/)
  assert.equal((sidebar.match(/window\.location\.reload\(\)/g) || []).length, 1)
  assert.doesNotMatch(sidebar, /updateStatus\.phase !== "completed"[\s\S]{0,300}window\.location\.reload\(\)/)
  assert.match(sidebar, /updateStartedAtRef\.current > 0/)
  assert.match(sidebar, /status\.completedAt[\s\S]{0,120}updateStartedAtRef\.current/)
  assert.match(sidebar, /status\.phase === "completed" && !completedInThisPage \? \{ phase: "idle"/)
})

test('旧破甲侧栏、RPC 和卡片入口已删除', () => {
  assert.doesNotMatch(clientSource, /BoundaryPromptTab|listBoundaryPrompts|从预设提取破甲/)
  assert.equal((clientSource.match(/dsh-tavern:boundary-prompts/g) || []).length, 1)
  assert.doesNotMatch(serverSource, /createBoundaryPromptModule|listBoundaryPrompts|tavern_update_boundary_prompt/)
  assert.match(clientSource, /tab\.type === "dsh-tavern:boundary-prompts".*retiredTabs\.push/)
  assert.match(clientSource, /betterSidebar\.closeTab\(tabId/)
})

test('卡片编辑读取保留人物卡宏，只在游玩投影中展开', () => {
  const cardReader = between(serverSource, "name: 'tavern_read_card'", "name: 'tavern_read_card_raw'")
  const worldBookReader = between(serverSource, "name: 'tavern_read_worldbook'", "name: 'tavern_update_card'")

  assert.doesNotMatch(cardReader, /projectCardMacros|projectCardText/)
  assert.doesNotMatch(worldBookReader, /projectCardMacros|projectCardText/)
})

test('预设库分别呈现酒馆标注界面与 DSH 预览界面', () => {
  const panel = between(clientSource, 'function PresetLibraryTab', 'function CardLibraryTab')

  assert.match(clientSource, /id: "dsh-tavern:presets"/)
  assert.match(clientSource, /title: "预设库"/)
  assert.match(panel, /rpc\("listPresets"/)
  assert.match(panel, /rpc\("getPreset"/)
  assert.match(panel, /rpc\("updatePresetEntry"/)
  assert.match(panel, /rpc\("previewPresetConversion"/)
  assert.match(panel, /前 · 稳定前缀/)
  assert.match(panel, /中 · 每轮注入/)
  assert.match(panel, /后 · 请求附加/)
  assert.match(panel, /酒馆原始预设/)
  assert.match(panel, /DSH 预设预览/)
  assert.match(panel, /破限相关/)
  assert.doesNotMatch(panel, /确认把.*标为破限相关/)
  assert.match(panel, /rpc\("importPreset"/)
  assert.match(panel, /rpc\("deletePreset"/)
  assert.match(panel, /SYSTEM|role\.toUpperCase/)
  assert.match(panel, /占位/)
  assert.match(panel, /rpc\("disableAllPresets"/)
  assert.match(panel, /先标注需要保留的破限提示词/)
  assert.match(panel, /条目的开启或关闭继承酒馆预设/)
  assert.match(panel, /正则沿用原预设设置/)
  assert.match(panel, /checked: entry\.runtimeIncluded/)
  assert.match(panel, /checked: sourceEntry\.enabled/)
  assert.match(panel, /checked: runtimeScript\.runtimeEnabled/)
  assert.match(panel, /编辑此条/)
  assert.match(panel, /保存修改/)
  assert.match(panel, /放弃修改/)
  assert.match(panel, /entryDraft\.role/)
  assert.match(panel, /entryDraft\.content/)
  assert.match(panel, /开启 " \+ item\.enabledCount/)
  assert.match(panel, /正则脚本/)
  assert.match(panel, /当前启用预设/)
  assert.match(panel, /不启用外部预设/)
  assert.match(panel, /regexScripts/)
  assert.match(panel, /查找正则/)
  assert.match(panel, /替换内容/)
  assert.match(serverSource, /regexCount: preset\.regexCount/)
  assert.match(serverSource, /enabledCount: preset\.enabledCount/)
  assert.match(serverSource, /enabledRegexCount: preset\.enabledRegexCount/)
  assert.match(serverSource, /case 'savePresetPlan'/)
  assert.match(serverSource, /case 'updatePresetEntry'/)
  assert.match(serverSource, /case 'applyPresetPlan'/)
  assert.match(serverSource, /runtimePresets\.applyPlan/)
  assert.match(panel, /props\.appendMention\("preset", item\.path, item\.title\)/)
  assert.ok(panel.indexOf('"提示词条目 · "') < panel.indexOf('"正则脚本 · "'))
  assert.doesNotMatch(panel, /exportPreset|dragstart|draggable/)
  assert.match(serverSource, /name: 'tavern_read_preset'/)
  assert.match(serverSource, /name: 'tavern_update_preset'/)
  assert.match(serverSource, /name: 'tavern_update_worldbook'/)
})

test('DSH 预览保留自动分段诊断与兼容信息', () => {
  const panel = between(clientSource, 'function PresetLibraryTab', 'const presetLibraryFeature')
  assert.match(panel, /兼容信息/)
  assert.match(panel, /当前顺序/)
  assert.match(panel, /其他顺序配置/)
  assert.doesNotMatch(panel, /顶层参数/)
  assert.doesNotMatch(panel, /扩展配置（含预设正则）/)
  assert.match(panel, /正则 · /)
  assert.match(panel, /查找表达式/)
  assert.match(panel, /替换内容/)
  assert.match(panel, /仅提示词/)
  assert.match(panel, /仅 Markdown/)
  assert.match(panel, /runtimeScript\.runtimeEnabled/)
  assert.match(panel, /DSH 预设预览/)
  assert.match(presetConversionSource, /人物卡或世界书占位符由系统自动提供/)
})

test('卡片模式预加载人物卡、预设、世界书和剧本四个库', () => {
  assert.match(clientSource, /readyCardSession/)
  assert.match(clientSource, /props\.openCardLibraryTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openResourcesTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openPresetLibraryTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openWorldBookLibraryTab\(readyCardSession\)/)
  assert.doesNotMatch(clientSource, /openBoundaryLibraryTab/)
  assert.ok(clientSource.indexOf('props.openCardLibraryTab(readyCardSession)') < clientSource.indexOf('props.openResourcesTab(readyCardSession)'))
  assert.match(clientSource, /openCardLibraryTab: function \(sessionId\) \{ ctx\.betterSidebar\.openTab\(\{ type: "dsh-tavern:cards" \}/)
  assert.match(clientSource, /ctx\.betterSidebar\.updateTab\("dsh-tavern:cards", \{ meta: null \}\)/)
  assert.match(clientSource, /registerTab\(\{\s*id: "dsh-tavern:resources"/)
  assert.match(clientSource, /id: "dsh-tavern:resources",\s*title: "剧本库"/)
  assert.match(clientSource, /id: "dsh-tavern:worldbooks",\s*title: "世界书库"/)
  assert.match(clientSource, /function reconcileLibraryTabTitles\(\)/)
  assert.match(clientSource, /"dsh-tavern:resources": "剧本库"/)
  assert.match(clientSource, /subscribeState\(reconcileLibraryTabTitles\)/)
  assert.match(clientSource, /openTab\(\{ type: "dsh-tavern:resources" \}/)
  assert.doesNotMatch(clientSource, /openTab\(\{ type: "editor", id: "dsh-tavern:files"/)
  assert.match(clientSource, /group\("剧本", "source", resources\.resources/)
  assert.doesNotMatch(clientSource, /group\("素材", "source"/)
  assert.doesNotMatch(clientSource, /group\("剧本", "script"/)
  assert.match(clientSource, /kind === "worldbook".*tavern-worldbook:/)
  assert.match(clientSource, /: "@\\\"" \+ safePath \+ "\\\""/)
  assert.match(clientSource, /body\.dsh-tavern-shell-active \[data-ref-chip="file"\].*max-width: calc\(100% - 4px\).*text-overflow: ellipsis/s)
  assert.match(clientSource, /\.dsh-tavern-candidate-question \{ max-width: 680px; \}/)
  assert.match(clientSource, /rpc\("importSource"/)
  assert.match(clientSource, /已绑定：/)
  assert.match(clientSource, /未绑定/)
  assert.match(clientSource, /rpc\("getResource", \{ path: item\.path \}/)
  assert.match(clientSource, /"← 返回剧本库"/)
  assert.match(clientSource, /setOpenedScript\(null\)/)
  assert.doesNotMatch(clientSource, /props\.openResource\(item\.previewPath, label\)/)
  assert.match(clientSource, /function parseTextResourceFile/)
  assert.match(clientSource, /\.txt,\.md,\.json,\.epub/)
  assert.match(clientSource, /application\/epub\+zip/)
})

test('剧本库可以把未绑定剧本绑定给未绑定人物卡，并可直接解绑', () => {
  const library = between(clientSource, 'function TavernResourcesTab', 'function register(input)')

  assert.match(library, /rpc\("listCards"/)
  assert.match(library, /card\.script == null/)
  assert.match(library, /rpc\("bindScript", \{ cardPath: cardPath, path: item\.path \}/)
  assert.match(library, /rpc\("deleteScript", \{ cardPath: boundCard\.path \}/)
  assert.match(library, /"绑定人物卡"/)
  assert.match(library, /"解绑"/)
})

test('人物卡库可以查看详情，并在当前卡片对话中引用人物卡', () => {
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')

  assert.match(library, /loadCard\(item\.path\)/)
  assert.match(library, /setLoading\(true\)/)
  assert.match(library, /rpcWithTimeout\("getCard", \{ path: path \}\)/)
  assert.match(library, /"重新读取"/)
  assert.match(library, /window\.addEventListener\("focus", onActivate\)/)
  assert.match(library, /在对话中引用/)
  assert.match(library, /props\.appendMention\(item\.path, item\.name\)/)
  assert.match(clientSource, /在对话中引用/)
  assert.match(clientSource, /requestedPath/)
  assert.match(clientSource, /loadCard\(requestedPath\)/)
})

test('人物卡 Agent 保存后重新读取已打开的详情，未变化时不重置表单', () => {
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')
  const listener = between(library, 'function onData()', 'window.addEventListener("dsh-tavern-data-changed"')

  assert.match(listener, /loadCard\(selectedPath\)/)
  assert.match(library, /setCard\(function \(current\)/)
  assert.match(library, /JSON\.stringify\(current\) === JSON\.stringify\(next\) \? current : next/)
})

test('删除对话时把缺失 Session 视为已经归档，并继续清理 Tavern 对话', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const deletion = between(sidebar, 'async function deleteConversation', 'async function exportCard')

  assert.match(sidebar, /function isMissingSessionArchiveError\(error\)/)
  assert.match(deletion, /catch \(archiveError\)/)
  assert.match(deletion, /if \(!isMissingSessionArchiveError\(archiveError\)\) throw archiveError/)
  assert.ok(deletion.indexOf('props.archiveSession(item.sessionId)') < deletion.indexOf('call("deleteChat", { chatId: item.chatId })'))
  assert.match(deletion, /props\.sessions\.clear\(\)/)
})

test('Session 顶栏工具区可以把服务端投影后的纯对话下载为 TXT', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const exporter = between(clientSource, 'function TavernConversationExportAction', 'function TavernPlayerNameAction')

  assert.match(serverSource, /case 'exportConversation': return await exportConversation/)
  assert.match(exporter, /rpc\("getSession", \{\}, props\.sessionId\)/)
  assert.match(exporter, /rpc\("exportConversation", \{ title: summary && summary\.displayTitle \|\| "" \}, props\.sessionId\)/)
  assert.match(exporter, /text\/plain;charset=utf-8/)
  assert.match(exporter, /new Blob\(\["\\uFEFF", result\.text\]/)
  assert.match(exporter, /"纯对话 TXT ↓"/)
  assert.match(clientSource, /slots\.inject\("conversation\.session\.header\.utilities"/)
  assert.match(clientSource, /id: "dsh-tavern-conversation-export"/)
  assert.doesNotMatch(sidebar, /导出 TXT|exportConversation/)
})

test('人物卡库通过列表进入详情，世界书编辑跳转到独立世界书库', () => {
  assert.match(clientSource, /id: "dsh-tavern:cards",\s*title: "人物卡库"/)
  assert.match(clientSource, /function CardLibraryTab/)
  assert.match(clientSource, /rpcWithTimeout\("getCard", \{ path: path \}\)/)
  assert.match(clientSource, /"基本信息"/)
  assert.match(clientSource, /"选择已有剧本"/)
  assert.match(clientSource, /call\("bindScript"/)
  assert.match(clientSource, /"导入新剧本并绑定"/)
  assert.match(serverSource, /Object\.assign\(\{\}, info, \{ path: script\.path \}\)/)
  assert.match(clientSource, /className: "dsh-tavern-script-hero"/)
  assert.match(clientSource, /h\("details", \{ className: "dsh-tavern-script-hero" \}/)
  assert.match(clientSource, /script \? \("剧本模式 · " \+ script\.title\) : "剧本模式 · 未绑定"/)
  assert.match(clientSource, /绑定剧本后，新开的游玩对话会自动进入剧本模式/)
  assert.match(clientSource, /更换或解绑会影响所有使用这张人物卡的剧本对话/)
  assert.match(clientSource, /"世界书 · " \+ worldBookEntries\.length/)
  assert.match(clientSource, /const hasWorldBookBinding = Boolean/)
  assert.match(clientSource, /hasWorldBookBinding \? null : h\("select"/)
  assert.match(clientSource, /hasWorldBookBinding \? null : h\("button", \{ className: "dsh-tavern-script-primary"/)
  assert.match(clientSource, /"打开世界书"/)
  assert.match(clientSource, /props\.onOpenWorldBook\(worldBookBinding\.source\)/)
  assert.match(clientSource, /worldBookSource: source/)
  assert.match(clientSource, /"重命名文件"/)
  assert.match(clientSource, /"导出"/)
  assert.match(clientSource, /"删除"/)
})

test('人物卡全部字段合并在默认展开的基本信息中，并位于世界书上方', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  const basic = panel.indexOf('h("summary", null, "基本信息")')
  const alternateGreetings = panel.indexOf('F("alternate_greetings"')
  const creatorNotes = panel.indexOf('F("creator_notes"')
  const worldBook = panel.indexOf('h("summary", null, "世界书 · "')

  assert.ok(basic >= 0)
  assert.ok(alternateGreetings > basic)
  assert.ok(creatorNotes > alternateGreetings)
  assert.ok(worldBook > creatorNotes)
  assert.doesNotMatch(panel, /h\("summary", null, "高级字段"\)/)
})

test('人物卡详情只提交用户实际改动，避免投影往返覆盖完整 raw', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  assert.match(panel, /const baseline = \{/)
  assert.match(panel, /JSON\.stringify\(next\[key\]\) !== JSON\.stringify\(baseline\[key\]\)/)
  assert.match(panel, /call\("updateCard", \{ path: cardPath, patch: patch \}\)/)
})

test('人物卡稳定前缀升级到 v3，旧会话会按新的字段边界重建', () => {
  assert.match(serverSource, /Number\(chat\.cardContextSnapshotVersion\) >= 3/)
  assert.equal((serverSource.match(/cardContextSnapshotVersion = 3/g) || []).length, 2)
})

test('世界书库统一编辑独立世界书与人物卡内置世界书', () => {
  const cardPanel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  const library = between(clientSource, 'function WorldBookEditor', 'function CardLibraryTab')
  assert.doesNotMatch(cardPanel, /setBookEntry|addBookEntry|editingWorldBookKey/)
  assert.match(cardPanel, /人物卡有自带世界书时默认绑定自带内容/)
  assert.match(library, /function WorldBookLibraryTab/)
  assert.match(library, /group\("独立世界书"/)
  assert.match(library, /group\("人物卡内置世界书"/)
  assert.match(library, /rpc\("importWorldBook"/)
  assert.match(library, /rpc\("updateWorldBook"/)
  assert.match(library, /const \[catalog, setCatalog\] = React\.useState\(null\)/)
  assert.match(library, /rpcWithTimeout\("listWorldBooks"/)
  assert.match(library, /rpcWithTimeout\("getWorldBookAssociations"/)
  assert.match(library, /"绑定人物卡"/)
  assert.match(library, /该世界书已经绑定人物卡/)
  assert.match(library, /rpc\("bindWorldBook"/)
  assert.match(library, /rpc\("unbindWorldBook"/)
  assert.match(library, /"正在读取世界书…"/)
  assert.match(library, /"重新读取"/)
  assert.match(library, /window\.addEventListener\("focus", onActivate\)/)
  assert.match(library, /未知字段与 extensions 会原样保留/)
})

test('资料库读取 RPC 有超时收尾，不会永久停留在加载状态', () => {
  const timeout = between(clientSource, 'function rpcWithTimeout', 'function createLiveTavernViewModule')

  assert.match(timeout, /new AbortController\(\)/)
  assert.match(timeout, /window\.setTimeout/)
  assert.match(timeout, /读取超时，请重新读取/)
  assert.match(timeout, /window\.clearTimeout/)
})

test('世界书条目的低频匹配开关默认收进兼容字段', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const compatibility = editor.indexOf('h("details", null, h("summary", null, "兼容字段")')

  assert.ok(compatibility >= 0)
  for (const label of ['"二级触发词"', '"启用"', '"使用二级条件"', '"区分大小写"', '"整词匹配"']) {
    assert.ok(editor.indexOf(label) > compatibility)
  }
  assert.doesNotMatch(editor.slice(compatibility, compatibility + 80), /open:/)
})

test('世界书条目默认只显示标题，新建条目初始展开', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const row = between(editor, 'function entryRow', 'return h("div", { className: "dsh-tavern-library" }')

  assert.match(row, /return h\("details", \{ key: entry\.ref, className: "dsh-tavern-worldbook-entry", defaultOpen: String\(entry\.ref\)\.startsWith\("new:"\) \}/)
  assert.match(row, /h\("summary", \{ className: "dsh-tavern-worldbook-entry-head" \}, entry\.comment \|\| entry\.title \|\| "未命名条目"\)/)
  assert.ok(row.indexOf('dsh-tavern-worldbook-entry-body') < row.indexOf('"标题 / 备注"'))
  assert.ok(row.indexOf('dsh-tavern-worldbook-entry-body') < row.indexOf('"内容"'))
})

test('世界书条目删除位于展开区底部并要求二次确认', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const row = between(editor, 'function entryRow', 'return h("div", { className: "dsh-tavern-library" }')

  assert.match(editor, /window\.confirm\(/)
  assert.match(editor, /"删除世界书条目“" \+ title/)
  assert.match(editor, /保存世界书后才会正式删除/)
  assert.match(row, /className: "dsh-tavern-worldbook-danger-zone"/)
  assert.match(row, /"删除条目"/)
  assert.ok(row.indexOf('"兼容字段"') < row.indexOf('dsh-tavern-worldbook-danger-zone'))
})

test('酒馆状态页等待会话绑定就绪后自动刷新', () => {
  const statusTab = between(clientSource, 'function TavernStatusTab', 'const candidatePanel')
  const statusPanel = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')

  assert.match(statusTab, /props\.sessions\.list\.subscribe/)
  assert.match(statusTab, /props\.sessions\.binding\(props\.sessionId\)/)
  assert.match(statusPanel, /useLiveTavernView\(props\.sessionId, stateKey\)/)
  assert.match(statusPanel, /loadState = liveState\.phase/)
  assert.doesNotMatch(statusPanel, /rpc\("getSession"/)
  assert.match(statusPanel, /正在重新连接酒馆状态/)
  assert.match(statusPanel, /重新加载/)
})

test('酒馆状态只服务游玩模式，卡片工作台面板暂不复用该侧栏', () => {
  const status = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
  const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
  assert.match(status, /if \(view\.mode === "card"\) return null;/)
  assert.match(view, /worldBookError: chat\.worldBookError \|\| null/)
  assert.match(status, /世界书召回失败：/)
})

test('剧本预览只显示当前召回和后续块', () => {
  assert.match(clientSource, /index === 0 \? "当前召回" : "后续"/)
  assert.doesNotMatch(clientSource, /上一块（已召回）|当前待召回|scriptPreview\.previous/)
})
