/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TavernSessionSignalFrame } from 'dsh-tavern-remote/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$74617665726e5369676e616c73 {
    follow: (sessionIds: readonly string[], signal?: AbortSignal) => AsyncIterable<TavernSessionSignalFrame>
  }
  interface TypertRemoteMap {
    'tavernSignals/follow': (sessionIds: readonly string[], signal?: AbortSignal) => AsyncIterable<TavernSessionSignalFrame>
  }
  interface TypertRemoteNamespaceMap {
    'tavernSignals': TypertRemoteNamespace$74617665726e5369676e616c73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
