/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const TavernJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => TavernJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => TavernJsonValueRemoteCodec$schema))])
const dsh_tavern_remote_tavernSignals_follow_parameter_0$schema = z.array(z.string())
const dsh_tavern_remote_tavernSignals_follow_result$schema = z.union([z.object({
  'type': z.literal("snapshot").readonly(),
  'signals': z.array(z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'kind': z.string().readonly(),
  'version': z.string().readonly(),
  'snapshot': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => TavernJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => TavernJsonValueRemoteCodec$schema))])), z.record(z.string(), z.lazy(() => TavernJsonValueRemoteCodec$schema))]).readonly().optional(),
})).readonly(),
}), z.object({
  'type': z.literal("delta").readonly(),
  'signal': z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'kind': z.string().readonly(),
  'version': z.string().readonly(),
  'snapshot': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => TavernJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => TavernJsonValueRemoteCodec$schema))])), z.record(z.string(), z.lazy(() => TavernJsonValueRemoteCodec$schema))]).readonly().optional(),
}).readonly(),
})])

export const TYPERT = {
  package: 'dsh-tavern-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-tavern-remote#tavernSignals/follow',
      service: 'tavernSignalRemote',
      namespace: 'tavernSignals',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionIds',
          wire: 'sessionIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-remote#tavernSignals/follow:sessionIds',
            schema: dsh_tavern_remote_tavernSignals_follow_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-remote/types#TavernSessionSignalFrame',
        schema: dsh_tavern_remote_tavernSignals_follow_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-tavern-remote/src/index.ts","line":20,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "tavernSessionSignals",
        "exportName": "TavernSessionSignalSource",
        "members": [
          {
            "kind": "method",
            "name": "follow",
            "signature": "follow(sessionIds: readonly string[], signal: AbortSignal): AsyncIterable<TavernSessionSignalFrame>"
          }
        ],
        "types": [
          {
            "name": "TavernJsonValue",
            "declaration": "export type TavernJsonValue = null | boolean | number | string | TavernJsonValue[] | { [key: string]: TavernJsonValue; };"
          },
          {
            "name": "TavernSessionSignal",
            "declaration": "export interface TavernSessionSignal {\n    readonly id: string;\n    readonly sessionId: string;\n    readonly kind: string;\n    readonly version: string;\n    readonly snapshot?: TavernJsonValue;\n}"
          },
          {
            "name": "TavernSessionSignalFrame",
            "declaration": "export type TavernSessionSignalFrame = { readonly type: 'snapshot'; readonly signals: readonly TavernSessionSignal[]; } | { readonly type: 'delta'; readonly signal: TavernSessionSignal; };"
          }
        ]
      },
      {
        "tags": [],
        "key": "tavernSignalRemote",
        "exportName": "TavernSessionSignalRemote",
        "members": [
          {
            "kind": "method",
            "name": "follow",
            "signature": "@Remote({ mode: 'stream' }) follow(sessionIds: readonly string[], signal: AbortSignal): AsyncIterable<TavernSessionSignalFrame>"
          }
        ],
        "types": [
          {
            "name": "TavernJsonValue",
            "declaration": "export type TavernJsonValue = null | boolean | number | string | TavernJsonValue[] | { [key: string]: TavernJsonValue; };"
          },
          {
            "name": "TavernSessionSignal",
            "declaration": "export interface TavernSessionSignal {\n    readonly id: string;\n    readonly sessionId: string;\n    readonly kind: string;\n    readonly version: string;\n    readonly snapshot?: TavernJsonValue;\n}"
          },
          {
            "name": "TavernSessionSignalFrame",
            "declaration": "export type TavernSessionSignalFrame = { readonly type: 'snapshot'; readonly signals: readonly TavernSessionSignal[]; } | { readonly type: 'delta'; readonly signal: TavernSessionSignal; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
